# Generated by Django 3.1.7 on 2024-02-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
    ]
