# Generated by Django 3.1.7 on 2024-02-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0002_auto_20240220_1437'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
    ]
