# Generated by Django 3.1.7 on 2024-02-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0003_auto_20240220_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='region',
        ),
    ]
