# Generated by Django 3.1.7 on 2024-02-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shp', '0004_delete_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='literarymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='维度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
            ],
        ),
    ]
